/**
 * app/api/pdf/[...path]/route.ts — GET download route for PDFs generated by
 * the pdf_create tool into workspace/exports.
 *
 * ToolEventCard links reference this as `/api/pdf/<relative-path-under-exports>`,
 * e.g. a pdf_create result `{ path: "exports/report-123.pdf" }` downloads at
 * `/api/pdf/report-123.pdf`.
 */

import type { NextRequest } from "next/server";
import { NextResponse } from "next/server";
import { readFile, stat } from "node:fs/promises";
import path from "node:path";
import { WorkspacePathError, resolveWorkspacePath } from "@/lib/server/workspace";

export const runtime = "nodejs";

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ path: string[] }> }
) {
  const { path: segments } = await params;
  if (!segments || segments.length === 0) {
    return NextResponse.json({ error: "Missing file path." }, { status: 400 });
  }

  const relPath = path.posix.join("exports", ...segments);

  let absPath: string;
  try {
    absPath = resolveWorkspacePath(relPath);
  } catch (err) {
    if (err instanceof WorkspacePathError) {
      return NextResponse.json({ error: err.message }, { status: 400 });
    }
    return NextResponse.json({ error: "Invalid path." }, { status: 400 });
  }

  try {
    const stats = await stat(absPath);
    if (!stats.isFile()) {
      return NextResponse.json({ error: "Not found." }, { status: 404 });
    }
    const data = await readFile(absPath);
    return new NextResponse(new Uint8Array(data), {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `inline; filename="${path.basename(absPath)}"`,
        "Content-Length": String(stats.size),
      },
    });
  } catch {
    return NextResponse.json({ error: "Not found." }, { status: 404 });
  }
}
